# syntax=docker/dockerfile:1
ARG BASE_IMAGE=mcr.microsoft.com/playwright:v1.63.0-noble@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27
FROM ${BASE_IMAGE}
ARG PLAYWRIGHT_VERSION=1.63.0
WORKDIR /opt/playwright
RUN npm install --no-save --ignore-scripts @playwright/test@${PLAYWRIGHT_VERSION}
USER pwuser
CMD ["node", "node_modules/playwright/cli.js", "run-server", "--port", "3000", "--host", "0.0.0.0", "--unsafe"]
