[package]
name = "thelxinoe-desktop"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
tauri = { version = "2.11", features = [] }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
url = "2"
keyring = "4.1"
anyhow.workspace = true
uuid.workspace = true
sha2 = "0.11"
sevenz-rust2 = { version = "0.22.2", default-features = false }
futures-util = "0.3"
tauri-plugin-notification = "2"

[dev-dependencies]
thelxinoe-auth.workspace = true
thelxinoe-database.workspace = true
anyhow.workspace = true
